app_id: "11edfc90-8640-46bf-99ec-f72915a26845"
app_secret: "thtKGEFW14)-+wpzlDD911)"
redirect: "http://localhost:8000/Web_App/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"